// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface ApiGatewayV2ApiToLambdaFunctionConnectorArgs {
  source: aws.apigatewayv2.Api;

  target: aws.lambda.Function;

  sourceQualifier: string;
}

export class ApiGatewayV2ApiToLambdaFunctionConnector extends pulumi.ComponentResource {
  constructor(name: string, args: ApiGatewayV2ApiToLambdaFunctionConnectorArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-connectors:index:ApiGatewayV2ApiToLambdaFunctionConnector', name, args, opts);
    const qualifier = args.sourceQualifier ?? '*';

    new aws.lambda.Permission(`${name}-policy`, {
      statementId: 'ApiGatewayV2ApiToLambdaFunctionConnector',
      action: 'lambda:InvokeFunction',
      function: args.target.name,
      principal: 'apigateway.amazonaws.com',
      sourceArn: pulumi.interpolate`arn:${aws.getPartitionOutput().partition}:execute-api:${aws.getRegionOutput().name}:${aws.getCallerIdentityOutput().accountId}:${args.source.id}/${qualifier}`,
    });
    this.registerOutputs({});
  }
}