// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface AppSyncGraphQLApiToLambdaFunctionConnectorArgs {
  /**
   * The source resource.
   */
  source: aws.appsync.GraphQLApi;

  /**
   * The target resource.
   */
  target: aws.lambda.Function;
}

/**
 * Connect a AppSync GraphQLApi to a Lambda Function.
 */
export class AppSyncGraphQLApiToLambdaFunctionConnector extends pulumi.ComponentResource {
  constructor(name: string, args: AppSyncGraphQLApiToLambdaFunctionConnectorArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-connectors:index:AppSyncGraphQLApiToLambdaFunctionConnector', name, args, opts);
    new aws.lambda.Permission(`${name}-policy`, {
      statementId: 'AppSyncGraphQLApiToLambdaFunctionConnector',
      action: 'lambda:InvokeFunction',
      function: args.target.name,
      principal: 'appsync.amazonaws.com',
      sourceArn: pulumi.interpolate`arn:${aws.getPartitionOutput({}, opts).partition}:appsync:${aws.getRegionOutput({}, opts).name}:${aws.getCallerIdentityOutput({}, opts).accountId}:apis/${args.source.id}`,
    }, opts);
    this.registerOutputs({});
  }
}