// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface AppSyncDataSourceToLambdaFunctionConnectorReadWriteArgs {
  source: aws.appsync.DataSource;

  target: aws.lambda.Function;

}

export class AppSyncDataSourceToLambdaFunctionConnectorReadWrite extends pulumi.ComponentResource {
  constructor(name: string, args: AppSyncDataSourceToLambdaFunctionConnectorReadWriteArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-connectors:index:AppSyncDataSourceToLambdaFunctionConnectorReadWrite', name, args, opts);
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.source.serviceRoleArn.apply(arn => arn!),
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'lambda:InvokeAsync',
              'lambda:InvokeFunction',
            ],
            Resource: [
              pulumi.interpolate`${args.target.arn}`,
              pulumi.interpolate`${args.target.arn}:*`,
            ],
          },
        ],
      }
    });
    this.registerOutputs({});
  }
}