// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface AppSyncGraphQLApiToLambdaFunctionConnectorArgs {
  source: aws.appsync.GraphQLApi;

  target: aws.lambda.Function;

}

export class AppSyncGraphQLApiToLambdaFunctionConnector extends pulumi.ComponentResource {
  constructor(name: string, args: AppSyncGraphQLApiToLambdaFunctionConnectorArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-connectors:index:AppSyncGraphQLApiToLambdaFunctionConnector', name, args, opts);
    new aws.lambda.Permission(`${name}-policy`, {
      statementId: 'AppSyncGraphQLApiToLambdaFunctionConnector',
      action: 'lambda:InvokeFunction',
      function: args.target.name,
      principal: 'appsync.amazonaws.com',
      sourceArn: pulumi.interpolate`arn:${aws.getPartitionOutput().partition}:appsync:${aws.getRegionOutput().name}:${aws.getCallerIdentityOutput().accountId}:apis/${args.source.id}`,
    });
    this.registerOutputs({});
  }
}