// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface AppSyncDataSourceToEventsEventBusConnectorReadWriteArgs {
  source: aws.appsync.DataSource;

  target: aws.cloudwatch.EventBus;

}

export class AppSyncDataSourceToEventsEventBusConnectorReadWrite extends pulumi.ComponentResource {
  constructor(name: string, args: AppSyncDataSourceToEventsEventBusConnectorReadWriteArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-connectors:index:AppSyncDataSourceToEventsEventBusConnectorReadWrite', name, args, opts);
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.source.serviceRoleArn.apply(arn => arn!),
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'events:PutEvents',
            ],
            Resource: [
              pulumi.interpolate`${args.target.arn}`,
            ],
          },
        ],
      }
    });
    this.registerOutputs({});
  }
}