// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface AppSyncDataSourceToDynamoDBTableConnectorReadWriteArgs {
  source: aws.appsync.DataSource;

  target: aws.dynamodb.Table;

}

export class AppSyncDataSourceToDynamoDBTableConnectorReadWrite extends pulumi.ComponentResource {
  constructor(name: string, args: AppSyncDataSourceToDynamoDBTableConnectorReadWriteArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-connectors:index:AppSyncDataSourceToDynamoDBTableConnectorReadWrite', name, args, opts);
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.source.serviceRoleArn.apply(arn => arn!),
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'dynamodb:GetItem',
              'dynamodb:Query',
              'dynamodb:Scan',
              'dynamodb:BatchGetItem',
              'dynamodb:ConditionCheckItem',
              'dynamodb:PartiQLSelect',
            ],
            Resource: [
              pulumi.interpolate`${args.target.arn}`,
              pulumi.interpolate`${args.target.arn}/index/*`,
            ],
          },
        ],
      }
    });
    this.registerOutputs({});
  }
}