// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface AppSyncDataSourceToLambdaFunctionConnectorArgs {
  /**
   * The source resource.
   */
  source: aws.appsync.DataSource;

  /**
   * The target resource.
   */
  target: aws.lambda.Function;
}

/**
 * Connect a AppSync DataSource to a Lambda Function.
 */
export class AppSyncDataSourceToLambdaFunctionConnector extends pulumi.ComponentResource {
  constructor(name: string, args: AppSyncDataSourceToLambdaFunctionConnectorArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-connectors:index:AppSyncDataSourceToLambdaFunctionConnector', name, args, opts);
    const statements: aws.iam.PolicyStatement[] = [];
    statements.push(
      {
        Effect: 'Allow',
        Action: [
          'lambda:InvokeAsync',
          'lambda:InvokeFunction',
        ],
        Resource: [
          pulumi.interpolate`${args.target.arn}`,
          pulumi.interpolate`${args.target.arn}:*`,
        ],
      },
    );
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.source.serviceRoleArn.apply(arn => arn!),
      policy: {
        Version: '2012-10-17',
        Statement: statements,
      }
    }, opts);
    this.registerOutputs({});
  }
}