// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface EventsRuleToSQSQueueConnectorArgs {
  source: aws.cloudwatch.EventRule;

  target: aws.sqs.Queue;

}

export class EventsRuleToSQSQueueConnector extends pulumi.ComponentResource {
  constructor(name: string, args: EventsRuleToSQSQueueConnectorArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-connectors:index:EventsRuleToSQSQueueConnector', name, args, opts);
    new aws.sqs.QueuePolicy(`${name}-policy`, {
      queueUrl: args.target.id,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'sqs:SendMessage',
            ],
            Resource: [
              pulumi.interpolate`${args.target.arn}`,
            ],
            Principal: {
              Service: 'events.amazonaws.com',
            },
            Condition: {
              ArnEquals: {
                'aws:SourceArn': args.source.arn,
              },
            },
          },
        ],
      }
    });
    this.registerOutputs({});
  }
}