// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface EventsRuleToLambdaFunctionConnectorArgs {
  source: aws.cloudwatch.EventRule;

  target: aws.lambda.Function;

}

export class EventsRuleToLambdaFunctionConnector extends pulumi.ComponentResource {
  constructor(name: string, args: EventsRuleToLambdaFunctionConnectorArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-connectors:index:EventsRuleToLambdaFunctionConnector', name, args, opts);
    new aws.lambda.Permission(`${name}-policy`, {
      statementId: 'EventsRuleToLambdaFunctionConnector',
      action: 'lambda:InvokeFunction',
      function: args.target.name,
      principal: 'events.amazonaws.com',
      sourceArn: pulumi.interpolate`${args.source.arn}`,
    });
    this.registerOutputs({});
  }
}