// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface EventsRuleToSfnStateMachineConnectorArgs {
  /**
   * The source resource.
   */
  source: aws.cloudwatch.EventRule;

  /**
   * The target resource.
   */
  target: aws.sfn.StateMachine;
}

/**
 * Connect a Events Rule to a StepFunctions StateMachine.
 */
export class EventsRuleToSfnStateMachineConnector extends pulumi.ComponentResource {
  constructor(name: string, args: EventsRuleToSfnStateMachineConnectorArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-connectors:index:EventsRuleToSfnStateMachineConnector', name, args, opts);
    const statements: aws.iam.PolicyStatement[] = [];
    statements.push(
      {
        Effect: 'Allow',
        Action: [
          'states:StartExecution',
        ],
        Resource: [
          pulumi.interpolate`${args.target.arn}`,
        ],
      },
    );
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.source.roleArn.apply(arn => arn!),
      policy: {
        Version: '2012-10-17',
        Statement: statements,
      }
    }, opts);
    this.registerOutputs({});
  }
}