// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface LambdaFunctionToLocationPlaceIndexConnectorArgs {
  /**
   * The source resource.
   */
  source: aws.lambda.Function;

  /**
   * The target resource.
   */
  target: aws.location.PlaceIndex;
}

/**
 * Connect a Lambda Function to a Location PlaceIndex.
 */
export class LambdaFunctionToLocationPlaceIndexConnector extends pulumi.ComponentResource {
  constructor(name: string, args: LambdaFunctionToLocationPlaceIndexConnectorArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-connectors:index:LambdaFunctionToLocationPlaceIndexConnector', name, args, opts);
    const statements: aws.iam.PolicyStatement[] = [];
    statements.push(
      {
        Effect: 'Allow',
        Action: [
          'geo:DescribePlaceIndex',
          'geo:GetPlace',
          'geo:SearchPlaceIndexForPosition',
          'geo:SearchPlaceIndexForSuggestions',
          'geo:SearchPlaceIndexForText',
        ],
        Resource: [
          pulumi.interpolate`${args.target.indexArn}`,
        ],
      },
    );
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.source.role,
      policy: {
        Version: '2012-10-17',
        Statement: statements,
      }
    }, opts);
    this.registerOutputs({});
  }
}