// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface LambdaFunctionToLocationPlaceIndexConnectorReadWriteArgs {
  source: aws.lambda.Function;

  target: aws.location.PlaceIndex;

}

export class LambdaFunctionToLocationPlaceIndexConnectorReadWrite extends pulumi.ComponentResource {
  constructor(name: string, args: LambdaFunctionToLocationPlaceIndexConnectorReadWriteArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-connectors:index:LambdaFunctionToLocationPlaceIndexConnectorReadWrite', name, args, opts);
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.source.role,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'geo:DescribePlaceIndex',
              'geo:GetPlace',
              'geo:SearchPlaceIndexForPosition',
              'geo:SearchPlaceIndexForSuggestions',
              'geo:SearchPlaceIndexForText',
            ],
            Resource: [
              pulumi.interpolate`${args.target.arn}`,
            ],
          },
        ],
      }
    });
    this.registerOutputs({});
  }
}