// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface LambdaFunctionToSNSTopicConnectorArgs {
  /**
   * The source resource.
   */
  source: aws.lambda.Function;

  /**
   * The target resource.
   */
  target: aws.sns.Topic;
}

/**
 * Connect a Lambda Function to a SNS Topic.
 */
export class LambdaFunctionToSNSTopicConnector extends pulumi.ComponentResource {
  constructor(name: string, args: LambdaFunctionToSNSTopicConnectorArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-connectors:index:LambdaFunctionToSNSTopicConnector', name, args, opts);
    const statements: aws.iam.PolicyStatement[] = [];
    statements.push(
      {
        Effect: 'Allow',
        Action: [
          'sns:Publish',
        ],
        Resource: [
          pulumi.interpolate`${args.target.arn}`,
        ],
      },
    );
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.source.role,
      policy: {
        Version: '2012-10-17',
        Statement: statements,
      }
    }, opts);
    this.registerOutputs({});
  }
}