// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface LambdaFunctionToS3BucketConnectorReadWriteArgs {
  source: aws.lambda.Function;

  target: aws.s3.Bucket;

}

export class LambdaFunctionToS3BucketConnectorReadWrite extends pulumi.ComponentResource {
  constructor(name: string, args: LambdaFunctionToS3BucketConnectorReadWriteArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-connectors:index:LambdaFunctionToS3BucketConnectorReadWrite', name, args, opts);
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.source.role,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              's3:GetObject',
              's3:GetObjectAcl',
              's3:GetObjectLegalHold',
              's3:GetObjectRetention',
              's3:GetObjectTorrent',
              's3:GetObjectVersion',
              's3:GetObjectVersionAcl',
              's3:GetObjectVersionForReplication',
              's3:GetObjectVersionTorrent',
              's3:ListBucket',
              's3:ListBucketMultipartUploads',
              's3:ListBucketVersions',
              's3:ListMultipartUploadParts',
            ],
            Resource: [
              pulumi.interpolate`${args.target.arn}`,
              pulumi.interpolate`${args.target.arn}/*`,
            ],
          },
        ],
      }
    });
    this.registerOutputs({});
  }
}