// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';
import { Access } from '../access';

export interface LambdaFunctionToSQSQueueConnectorArgs {
  /**
   * The source resource.
   */
  source: aws.lambda.Function;

  /**
   * The target resource.
   */
  target: aws.sqs.Queue;

  /**
   * The access level for the policy.
   *
   * @default Access.READ
   */
  access?: Access;
}

/**
 * Connect a Lambda Function to a SQS Queue.
 */
export class LambdaFunctionToSQSQueueConnector extends pulumi.ComponentResource {
  constructor(name: string, args: LambdaFunctionToSQSQueueConnectorArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-connectors:index:LambdaFunctionToSQSQueueConnector', name, args, opts);
    const access = args.access ?? Access.READ;

    const readPolicies: aws.iam.PolicyStatement[] = [];
    const writePolicies: aws.iam.PolicyStatement[] = [];
    readPolicies.push(
      {
        Effect: 'Allow',
        Action: [
          'sqs:ReceiveMessage',
          'sqs:GetQueueAttributes',
        ],
        Resource: [
          pulumi.interpolate`${args.target.arn}`,
        ],
      },
    );
    writePolicies.push(
      {
        Effect: 'Allow',
        Action: [
          'sqs:DeleteMessage',
          'sqs:SendMessage',
          'sqs:ChangeMessageVisibility',
          'sqs:PurgeQueue',
        ],
        Resource: [
          pulumi.interpolate`${args.target.arn}`,
        ],
      },
    );
    const statements: aws.iam.PolicyStatement[] = [];
    if (access === Access.READ || access === Access.READ_WRITE) {
      statements.push(...readPolicies);
    }
    if (access === Access.WRITE || access === Access.READ_WRITE) {
      statements.push(...writePolicies);
    }
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.source.role,
      policy: {
        Version: '2012-10-17',
        Statement: statements,
      }
    }, opts);
    this.registerOutputs({});
  }
}