// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface LambdaFunctionToStepFunctionsStateMachineConnectorReadWriteArgs {
  source: aws.lambda.Function;

  target: aws.sfn.StateMachine;

}

export class LambdaFunctionToStepFunctionsStateMachineConnectorReadWrite extends pulumi.ComponentResource {
  constructor(name: string, args: LambdaFunctionToStepFunctionsStateMachineConnectorReadWriteArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-connectors:index:LambdaFunctionToStepFunctionsStateMachineConnectorReadWrite', name, args, opts);
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.source.role,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'states:DescribeStateMachine',
              'states:ListExecutions',
            ],
            Resource: [
              pulumi.interpolate`${args.target.arn}`,
            ],
          },
          {
            Effect: 'Allow',
            Action: [
              'states:DescribeExecution',
              'states:DescribeStateMachineForExecution',
              'states:GetExecutionHistory',
            ],
            Resource: [
              pulumi.interpolate`arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:execution:${args.target.name}:*`,
            ],
          },
        ],
      }
    });
    this.registerOutputs({});
  }
}