// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';
import { Access } from '../access';

export interface LambdaFunctionToS3BucketConnectorArgs {
  /**
   * The source resource.
   */
  source: aws.lambda.Function;

  /**
   * The target resource.
   */
  target: aws.s3.Bucket;

  /**
   * The access level for the policy.
   *
   * @default Access.READ
   */
  access?: Access;
}

/**
 * Connect a Lambda Function to a S3 Bucket.
 */
export class LambdaFunctionToS3BucketConnector extends pulumi.ComponentResource {
  constructor(name: string, args: LambdaFunctionToS3BucketConnectorArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-connectors:index:LambdaFunctionToS3BucketConnector', name, args, opts);
    const access = args.access ?? Access.READ;

    const readPolicies: aws.iam.PolicyStatement[] = [];
    const writePolicies: aws.iam.PolicyStatement[] = [];
    readPolicies.push(
      {
        Effect: 'Allow',
        Action: [
          's3:GetObject',
          's3:GetObjectAcl',
          's3:GetObjectLegalHold',
          's3:GetObjectRetention',
          's3:GetObjectTorrent',
          's3:GetObjectVersion',
          's3:GetObjectVersionAcl',
          's3:GetObjectVersionForReplication',
          's3:GetObjectVersionTorrent',
          's3:ListBucket',
          's3:ListBucketMultipartUploads',
          's3:ListBucketVersions',
          's3:ListMultipartUploadParts',
        ],
        Resource: [
          pulumi.interpolate`${args.target.arn}`,
          pulumi.interpolate`${args.target.arn}/*`,
        ],
      },
    );
    writePolicies.push(
      {
        Effect: 'Allow',
        Action: [
          's3:AbortMultipartUpload',
          's3:DeleteObject',
          's3:DeleteObjectVersion',
          's3:PutObject',
          's3:PutObjectLegalHold',
          's3:PutObjectRetention',
          's3:RestoreObject',
        ],
        Resource: [
          pulumi.interpolate`${args.target.arn}`,
          pulumi.interpolate`${args.target.arn}/*`,
        ],
      },
    );
    const statements: aws.iam.PolicyStatement[] = [];
    if (access === Access.READ || access === Access.READ_WRITE) {
      statements.push(...readPolicies);
    }
    if (access === Access.WRITE || access === Access.READ_WRITE) {
      statements.push(...writePolicies);
    }
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.source.role,
      policy: {
        Version: '2012-10-17',
        Statement: statements,
      }
    }, opts);
    this.registerOutputs({});
  }
}