// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface SNSTopicToLambdaFunctionConnectorArgs {
  source: aws.sns.Topic;

  target: aws.lambda.Function;

}

export class SNSTopicToLambdaFunctionConnector extends pulumi.ComponentResource {
  constructor(name: string, args: SNSTopicToLambdaFunctionConnectorArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-connectors:index:SNSTopicToLambdaFunctionConnector', name, args, opts);
    new aws.lambda.Permission(`${name}-policy`, {
      statementId: 'SNSTopicToLambdaFunctionConnector',
      action: 'lambda:InvokeFunction',
      function: args.target.name,
      principal: 'sns.amazonaws.com',
      sourceArn: pulumi.interpolate`${args.source.arn}`,
    });
    this.registerOutputs({});
  }
}