// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';
import { Access } from '../access';

export interface SfnStateMachineToDynamoDBTableConnectorArgs {
  /**
   * The source resource.
   */
  source: aws.sfn.StateMachine;

  /**
   * The target resource.
   */
  target: aws.dynamodb.Table;

  /**
   * The access level for the policy.
   *
   * @default Access.READ
   */
  access?: Access;
}

/**
 * Connect a StepFunctions StateMachine to a DynamoDB Table.
 */
export class SfnStateMachineToDynamoDBTableConnector extends pulumi.ComponentResource {
  constructor(name: string, args: SfnStateMachineToDynamoDBTableConnectorArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-connectors:index:SfnStateMachineToDynamoDBTableConnector', name, args, opts);
    const access = args.access ?? Access.READ;

    const readPolicies: aws.iam.PolicyStatement[] = [];
    const writePolicies: aws.iam.PolicyStatement[] = [];
    readPolicies.push(
      {
        Effect: 'Allow',
        Action: [
          'dynamodb:GetItem',
          'dynamodb:Query',
          'dynamodb:Scan',
          'dynamodb:BatchGetItem',
          'dynamodb:ConditionCheckItem',
          'dynamodb:PartiQLSelect',
        ],
        Resource: [
          pulumi.interpolate`${args.target.arn}`,
          pulumi.interpolate`${args.target.arn}/index/*`,
        ],
      },
    );
    writePolicies.push(
      {
        Effect: 'Allow',
        Action: [
          'dynamodb:PutItem',
          'dynamodb:UpdateItem',
          'dynamodb:DeleteItem',
          'dynamodb:BatchWriteItem',
          'dynamodb:PartiQLDelete',
          'dynamodb:PartiQLInsert',
          'dynamodb:PartiQLUpdate',
        ],
        Resource: [
          pulumi.interpolate`${args.target.arn}`,
          pulumi.interpolate`${args.target.arn}/index/*`,
        ],
      },
    );
    const statements: aws.iam.PolicyStatement[] = [];
    if (access === Access.READ || access === Access.READ_WRITE) {
      statements.push(...readPolicies);
    }
    if (access === Access.WRITE || access === Access.READ_WRITE) {
      statements.push(...writePolicies);
    }
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.source.roleArn,
      policy: {
        Version: '2012-10-17',
        Statement: statements,
      }
    }, opts);
    this.registerOutputs({});
  }
}