// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface StepFunctionsStateMachineToStepFunctionsStateMachineConnectorReadWriteArgs {
  source: aws.sfn.StateMachine;

  target: aws.sfn.StateMachine;

}

export class StepFunctionsStateMachineToStepFunctionsStateMachineConnectorReadWrite extends pulumi.ComponentResource {
  constructor(name: string, args: StepFunctionsStateMachineToStepFunctionsStateMachineConnectorReadWriteArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-connectors:index:StepFunctionsStateMachineToStepFunctionsStateMachineConnectorReadWrite', name, args, opts);
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.source.roleArn,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'states:DescribeExecution',
            ],
            Resource: [
              pulumi.interpolate`arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:execution:${args.target.name}:*`,
            ],
          },
          {
            Effect: 'Allow',
            Action: [
              'events:DescribeRule',
            ],
            Resource: [
              'arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventsForStepFunctionsExecutionRule',
            ],
          },
        ],
      }
    });
    this.registerOutputs({});
  }
}