// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface StepFunctionsStateMachineToSNSTopicConnectorReadWriteArgs {
  source: aws.sfn.StateMachine;

  target: aws.sns.Topic;

}

export class StepFunctionsStateMachineToSNSTopicConnectorReadWrite extends pulumi.ComponentResource {
  constructor(name: string, args: StepFunctionsStateMachineToSNSTopicConnectorReadWriteArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-connectors:index:StepFunctionsStateMachineToSNSTopicConnectorReadWrite', name, args, opts);
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.source.roleArn,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'sns:Publish',
            ],
            Resource: [
              pulumi.interpolate`${args.target.arn}`,
            ],
          },
        ],
      }
    });
    this.registerOutputs({});
  }
}